# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2.1.3
        with:
          # Optional static site generator to attempt to configure: "nuxt", "next", "gatsby", or "sveltekit"
          static_site_generator: sveltekit
          # Optional file path to static site generator configuration file
          #generator_config_file: # optional
          # GitHub token
          #token: # default is ${{ github.token }}
          # Should a Pages site be enabled for the repository if not so already?
          #enablement: # optional, default is true
